source 'https://github.com/balazsmorv/SpotifySDKPodSpec.git'
source 'https://github.com/CocoaPods/Specs.git'


use_frameworks!

platform :ios, '9.0'

target 'SpotifyHelper_Example' do
  
  pod 'RxSwift', '~> 5.0'
  pod 'RxRelay', '~> 5.0'
  pod 'RxCocoa', '~> 5.0'
  pod 'RxGesture', '~> 3.0'




post_install do |installer|
  installer.pods_project.build_configurations.each do |config|
    config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
  end
end

  
  pod 'SpotifyHelper', :path => '../'

  target 'SpotifyHelper_Tests' do
    inherit! :search_paths

    
  end




end
